### ISSUE TITLE
Apple-Pay-Signature-Verification

### ISSUE THREAD

**Issue by Cris464** [zooz-mobile/Apple-Pay-Signature-Verification#1]
Hi while i execute this code, i am getting Exception  as mentioned below. please advice.

in thread "main" org.bouncycastle.cms.CMSException: IOException reading content.
    at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
    at org.bouncycastle.cms.CMSUtils.readContentInfo(Unknown Source)
    at org.bouncycastle.cms.CMSSignedData.<init>(Unknown Source)
    at ApplePaySignatureVerifier.validate(ApplePaySignatureVerifier.java:42)
    at Main.main(Main.java:47)
Caused by: java.io.IOException: DER length more than 4 bytes: 76
    at org.bouncycastle.asn1.ASN1InputStream.readLength(Unknown Source)
    at org.bouncycastle.asn1.ASN1StreamParser.readObject(Unknown Source)
    at org.bouncycastle.asn1.ASN1StreamParser.readVector(Unknown Source)

**Comment by zooz-mobile** [comment]
Hi
The token provided is an example how token should look like (paymentJsonData)
It's corrupted for security reason (as the readme says)

please replace it with your token.

**Comment by Cris464** [comment]
Thanks,
