### ISSUE TITLE
apple Pay signature

### ISSUE THREAD

**Issue by Cris464** [zooz-mobile/Apple-Pay-Signature-Verification#2]
Hi ,

I have given private static final String APPLE_ROOT_CA_G3_CER = "C:/PROJECTS/AppleRootCA-G3.cer"; in ApplePaySignatureVerifier class. 

When I execute this , the inputstream value is null.  The exception is as below.
Please advice. Thanks for quick response the grate help..

Exception in thread "main" java.security.cert.CertificateException: Missing input stream
    at sun.security.provider.X509Factory.engineGenerateCertificate(X509Factory.java:88)
    at java.security.cert.CertificateFactory.generateCertificate(CertificateFactory.java:339)
    at ApplePaySignatureVerifier.validate(ApplePaySignatureVerifier.java:66)
    at Main.main(Main.java:52)

**Comment by zooz-mobile** [comment]
Line 64 in ApplePaySignatureVerifier:
            inputStream = ApplePaySignatureVerifier.class.getClassLoader().getResourceAsStream(APPLE_ROOT_CA_G3_CER);

The file is loaded as resource of the class.
Either add G3 Certificate as resource or modify the code to load external file.
