### ISSUE TITLE
ApplePay signature.

### ISSUE THREAD

**Issue by Cris464** [zooz-mobile/Apple-Pay-Signature-Verification#3]
HI,

What exactly should i change in my data, to over code this exception and execute my code sucessfully. Please advice.

Exception in thread "main" java.lang.Exception: apple pay signature is too old, the expiration time is: 60000 ms
    at ApplePaySignatureVerifier.validateSignatureTime(ApplePaySignatureVerifier.java:136)
    at ApplePaySignatureVerifier.validate(ApplePaySignatureVerifier.java:89)
    at Main.main(Main.java:52)

**Comment by zooz-mobile** [comment]
One of the steps (step 5) in the signature verification is to make sure the signature is fresh.
You can create new signature and try it, or you can change the 60000ms to something bigger (60000ms = 1 Minutes)

**Comment by Cris464** [comment]
Thank you.
